export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const MARK_COURSE_COMPLETED = 'MARK_COURSE_COMPLETED'
export const ENROLL_COURSE = 'ENROLL_COURSE'
export const FETCH_ENROLLED_COURSES = 'FETCH_ENROLLED_COURSES';